name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls
    # 0. checkout code from repo
    # 1. install dependencies
    # 2. execute automate test
